/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StallIndexRouteImport } from './routes/stall/index'
import { Route as SalesRealizationIndexRouteImport } from './routes/sales-realization/index'
import { Route as ProductPotentialIndexRouteImport } from './routes/product-potential/index'
import { Route as ProductKnowledgeIndexRouteImport } from './routes/product-knowledge/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminStallIndexRouteImport } from './routes/admin/stall/index'
import { Route as AdminSaleIndexRouteImport } from './routes/admin/sale/index'
import { Route as AdminProductIndexRouteImport } from './routes/admin/product/index'
import { Route as AdminLandIndexRouteImport } from './routes/admin/land/index'
import { Route as AdminCommodityIndexRouteImport } from './routes/admin/commodity/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as AdminSaleSaleDailyIndexRouteImport } from './routes/admin/sale/sale-daily/index'
import { Route as AdminRegionRegencyIndexRouteImport } from './routes/admin/region/regency/index'
import { Route as AdminRegionProvinceIndexRouteImport } from './routes/admin/region/province/index'
import { Route as AdminProductProductDosageIndexRouteImport } from './routes/admin/product/product-dosage/index'
import { Route as AdminProductProductBrandIndexRouteImport } from './routes/admin/product/product-brand/index'
import { Route as AdminLandRegencyLandIndexRouteImport } from './routes/admin/land/regency-land/index'
import { Route as AdminLandProvinceLandIndexRouteImport } from './routes/admin/land/province-land/index'
import { Route as AdminCommodityRegencyCommodityIndexRouteImport } from './routes/admin/commodity/regency-commodity/index'
import { Route as AdminCommodityProvinceCommodityIndexRouteImport } from './routes/admin/commodity/province-commodity/index'
import { Route as AdminLandProvinceLandLandTypeRouteImport } from './routes/admin/land/province-land/$landType'
import { ServerRoute as ApiSplatServerRouteImport } from './routes/api/$'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth.$'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StallIndexRoute = StallIndexRouteImport.update({
  id: '/stall/',
  path: '/stall/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRealizationIndexRoute = SalesRealizationIndexRouteImport.update({
  id: '/sales-realization/',
  path: '/sales-realization/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPotentialIndexRoute = ProductPotentialIndexRouteImport.update({
  id: '/product-potential/',
  path: '/product-potential/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductKnowledgeIndexRoute = ProductKnowledgeIndexRouteImport.update({
  id: '/product-knowledge/',
  path: '/product-knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStallIndexRoute = AdminStallIndexRouteImport.update({
  id: '/stall/',
  path: '/stall/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSaleIndexRoute = AdminSaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductIndexRoute = AdminProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLandIndexRoute = AdminLandIndexRouteImport.update({
  id: '/land/',
  path: '/land/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommodityIndexRoute = AdminCommodityIndexRouteImport.update({
  id: '/commodity/',
  path: '/commodity/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSaleSaleDailyIndexRoute = AdminSaleSaleDailyIndexRouteImport.update({
  id: '/sale/sale-daily/',
  path: '/sale/sale-daily/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegionRegencyIndexRoute = AdminRegionRegencyIndexRouteImport.update({
  id: '/region/regency/',
  path: '/region/regency/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegionProvinceIndexRoute =
  AdminRegionProvinceIndexRouteImport.update({
    id: '/region/province/',
    path: '/region/province/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductProductDosageIndexRoute =
  AdminProductProductDosageIndexRouteImport.update({
    id: '/product/product-dosage/',
    path: '/product/product-dosage/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductProductBrandIndexRoute =
  AdminProductProductBrandIndexRouteImport.update({
    id: '/product/product-brand/',
    path: '/product/product-brand/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLandRegencyLandIndexRoute =
  AdminLandRegencyLandIndexRouteImport.update({
    id: '/land/regency-land/',
    path: '/land/regency-land/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLandProvinceLandIndexRoute =
  AdminLandProvinceLandIndexRouteImport.update({
    id: '/land/province-land/',
    path: '/land/province-land/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommodityRegencyCommodityIndexRoute =
  AdminCommodityRegencyCommodityIndexRouteImport.update({
    id: '/commodity/regency-commodity/',
    path: '/commodity/regency-commodity/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommodityProvinceCommodityIndexRoute =
  AdminCommodityProvinceCommodityIndexRouteImport.update({
    id: '/commodity/province-commodity/',
    path: '/commodity/province-commodity/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLandProvinceLandLandTypeRoute =
  AdminLandProvinceLandLandTypeRouteImport.update({
    id: '/land/province-land/$landType',
    path: '/land/province-land/$landType',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/admin/': typeof AdminIndexRoute
  '/map': typeof MapIndexRoute
  '/product-knowledge': typeof ProductKnowledgeIndexRoute
  '/product-potential': typeof ProductPotentialIndexRoute
  '/sales-realization': typeof SalesRealizationIndexRoute
  '/stall': typeof StallIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/commodity': typeof AdminCommodityIndexRoute
  '/admin/land': typeof AdminLandIndexRoute
  '/admin/product': typeof AdminProductIndexRoute
  '/admin/sale': typeof AdminSaleIndexRoute
  '/admin/stall': typeof AdminStallIndexRoute
  '/admin/land/province-land/$landType': typeof AdminLandProvinceLandLandTypeRoute
  '/admin/commodity/province-commodity': typeof AdminCommodityProvinceCommodityIndexRoute
  '/admin/commodity/regency-commodity': typeof AdminCommodityRegencyCommodityIndexRoute
  '/admin/land/province-land': typeof AdminLandProvinceLandIndexRoute
  '/admin/land/regency-land': typeof AdminLandRegencyLandIndexRoute
  '/admin/product/product-brand': typeof AdminProductProductBrandIndexRoute
  '/admin/product/product-dosage': typeof AdminProductProductDosageIndexRoute
  '/admin/region/province': typeof AdminRegionProvinceIndexRoute
  '/admin/region/regency': typeof AdminRegionRegencyIndexRoute
  '/admin/sale/sale-daily': typeof AdminSaleSaleDailyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/admin': typeof AdminIndexRoute
  '/map': typeof MapIndexRoute
  '/product-knowledge': typeof ProductKnowledgeIndexRoute
  '/product-potential': typeof ProductPotentialIndexRoute
  '/sales-realization': typeof SalesRealizationIndexRoute
  '/stall': typeof StallIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/commodity': typeof AdminCommodityIndexRoute
  '/admin/land': typeof AdminLandIndexRoute
  '/admin/product': typeof AdminProductIndexRoute
  '/admin/sale': typeof AdminSaleIndexRoute
  '/admin/stall': typeof AdminStallIndexRoute
  '/admin/land/province-land/$landType': typeof AdminLandProvinceLandLandTypeRoute
  '/admin/commodity/province-commodity': typeof AdminCommodityProvinceCommodityIndexRoute
  '/admin/commodity/regency-commodity': typeof AdminCommodityRegencyCommodityIndexRoute
  '/admin/land/province-land': typeof AdminLandProvinceLandIndexRoute
  '/admin/land/regency-land': typeof AdminLandRegencyLandIndexRoute
  '/admin/product/product-brand': typeof AdminProductProductBrandIndexRoute
  '/admin/product/product-dosage': typeof AdminProductProductDosageIndexRoute
  '/admin/region/province': typeof AdminRegionProvinceIndexRoute
  '/admin/region/regency': typeof AdminRegionRegencyIndexRoute
  '/admin/sale/sale-daily': typeof AdminSaleSaleDailyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/admin/': typeof AdminIndexRoute
  '/map/': typeof MapIndexRoute
  '/product-knowledge/': typeof ProductKnowledgeIndexRoute
  '/product-potential/': typeof ProductPotentialIndexRoute
  '/sales-realization/': typeof SalesRealizationIndexRoute
  '/stall/': typeof StallIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/commodity/': typeof AdminCommodityIndexRoute
  '/admin/land/': typeof AdminLandIndexRoute
  '/admin/product/': typeof AdminProductIndexRoute
  '/admin/sale/': typeof AdminSaleIndexRoute
  '/admin/stall/': typeof AdminStallIndexRoute
  '/admin/land/province-land/$landType': typeof AdminLandProvinceLandLandTypeRoute
  '/admin/commodity/province-commodity/': typeof AdminCommodityProvinceCommodityIndexRoute
  '/admin/commodity/regency-commodity/': typeof AdminCommodityRegencyCommodityIndexRoute
  '/admin/land/province-land/': typeof AdminLandProvinceLandIndexRoute
  '/admin/land/regency-land/': typeof AdminLandRegencyLandIndexRoute
  '/admin/product/product-brand/': typeof AdminProductProductBrandIndexRoute
  '/admin/product/product-dosage/': typeof AdminProductProductDosageIndexRoute
  '/admin/region/province/': typeof AdminRegionProvinceIndexRoute
  '/admin/region/regency/': typeof AdminRegionRegencyIndexRoute
  '/admin/sale/sale-daily/': typeof AdminSaleSaleDailyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/demo/orpc-todo'
    | '/admin/'
    | '/map'
    | '/product-knowledge'
    | '/product-potential'
    | '/sales-realization'
    | '/stall'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/commodity'
    | '/admin/land'
    | '/admin/product'
    | '/admin/sale'
    | '/admin/stall'
    | '/admin/land/province-land/$landType'
    | '/admin/commodity/province-commodity'
    | '/admin/commodity/regency-commodity'
    | '/admin/land/province-land'
    | '/admin/land/regency-land'
    | '/admin/product/product-brand'
    | '/admin/product/product-dosage'
    | '/admin/region/province'
    | '/admin/region/regency'
    | '/admin/sale/sale-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/demo/orpc-todo'
    | '/admin'
    | '/map'
    | '/product-knowledge'
    | '/product-potential'
    | '/sales-realization'
    | '/stall'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/commodity'
    | '/admin/land'
    | '/admin/product'
    | '/admin/sale'
    | '/admin/stall'
    | '/admin/land/province-land/$landType'
    | '/admin/commodity/province-commodity'
    | '/admin/commodity/regency-commodity'
    | '/admin/land/province-land'
    | '/admin/land/regency-land'
    | '/admin/product/product-brand'
    | '/admin/product/product-dosage'
    | '/admin/region/province'
    | '/admin/region/regency'
    | '/admin/sale/sale-daily'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/demo/orpc-todo'
    | '/admin/'
    | '/map/'
    | '/product-knowledge/'
    | '/product-potential/'
    | '/sales-realization/'
    | '/stall/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/commodity/'
    | '/admin/land/'
    | '/admin/product/'
    | '/admin/sale/'
    | '/admin/stall/'
    | '/admin/land/province-land/$landType'
    | '/admin/commodity/province-commodity/'
    | '/admin/commodity/regency-commodity/'
    | '/admin/land/province-land/'
    | '/admin/land/regency-land/'
    | '/admin/product/product-brand/'
    | '/admin/product/product-dosage/'
    | '/admin/region/province/'
    | '/admin/region/regency/'
    | '/admin/sale/sale-daily/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  MapIndexRoute: typeof MapIndexRoute
  ProductKnowledgeIndexRoute: typeof ProductKnowledgeIndexRoute
  ProductPotentialIndexRoute: typeof ProductPotentialIndexRoute
  SalesRealizationIndexRoute: typeof SalesRealizationIndexRoute
  StallIndexRoute: typeof StallIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}
export interface FileServerRoutesByFullPath {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/$' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/$' | '/api/auth/$' | '/api/rpc/$'
  id: '__root__' | '/api/$' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stall/': {
      id: '/stall/'
      path: '/stall'
      fullPath: '/stall'
      preLoaderRoute: typeof StallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-realization/': {
      id: '/sales-realization/'
      path: '/sales-realization'
      fullPath: '/sales-realization'
      preLoaderRoute: typeof SalesRealizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-potential/': {
      id: '/product-potential/'
      path: '/product-potential'
      fullPath: '/product-potential'
      preLoaderRoute: typeof ProductPotentialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-knowledge/': {
      id: '/product-knowledge/'
      path: '/product-knowledge'
      fullPath: '/product-knowledge'
      preLoaderRoute: typeof ProductKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stall/': {
      id: '/admin/stall/'
      path: '/stall'
      fullPath: '/admin/stall'
      preLoaderRoute: typeof AdminStallIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sale/': {
      id: '/admin/sale/'
      path: '/sale'
      fullPath: '/admin/sale'
      preLoaderRoute: typeof AdminSaleIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product/': {
      id: '/admin/product/'
      path: '/product'
      fullPath: '/admin/product'
      preLoaderRoute: typeof AdminProductIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/land/': {
      id: '/admin/land/'
      path: '/land'
      fullPath: '/admin/land'
      preLoaderRoute: typeof AdminLandIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commodity/': {
      id: '/admin/commodity/'
      path: '/commodity'
      fullPath: '/admin/commodity'
      preLoaderRoute: typeof AdminCommodityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sale/sale-daily/': {
      id: '/admin/sale/sale-daily/'
      path: '/sale/sale-daily'
      fullPath: '/admin/sale/sale-daily'
      preLoaderRoute: typeof AdminSaleSaleDailyIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/region/regency/': {
      id: '/admin/region/regency/'
      path: '/region/regency'
      fullPath: '/admin/region/regency'
      preLoaderRoute: typeof AdminRegionRegencyIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/region/province/': {
      id: '/admin/region/province/'
      path: '/region/province'
      fullPath: '/admin/region/province'
      preLoaderRoute: typeof AdminRegionProvinceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product/product-dosage/': {
      id: '/admin/product/product-dosage/'
      path: '/product/product-dosage'
      fullPath: '/admin/product/product-dosage'
      preLoaderRoute: typeof AdminProductProductDosageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product/product-brand/': {
      id: '/admin/product/product-brand/'
      path: '/product/product-brand'
      fullPath: '/admin/product/product-brand'
      preLoaderRoute: typeof AdminProductProductBrandIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/land/regency-land/': {
      id: '/admin/land/regency-land/'
      path: '/land/regency-land'
      fullPath: '/admin/land/regency-land'
      preLoaderRoute: typeof AdminLandRegencyLandIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/land/province-land/': {
      id: '/admin/land/province-land/'
      path: '/land/province-land'
      fullPath: '/admin/land/province-land'
      preLoaderRoute: typeof AdminLandProvinceLandIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commodity/regency-commodity/': {
      id: '/admin/commodity/regency-commodity/'
      path: '/commodity/regency-commodity'
      fullPath: '/admin/commodity/regency-commodity'
      preLoaderRoute: typeof AdminCommodityRegencyCommodityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commodity/province-commodity/': {
      id: '/admin/commodity/province-commodity/'
      path: '/commodity/province-commodity'
      fullPath: '/admin/commodity/province-commodity'
      preLoaderRoute: typeof AdminCommodityProvinceCommodityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/land/province-land/$landType': {
      id: '/admin/land/province-land/$landType'
      path: '/land/province-land/$landType'
      fullPath: '/admin/land/province-land/$landType'
      preLoaderRoute: typeof AdminLandProvinceLandLandTypeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommodityIndexRoute: typeof AdminCommodityIndexRoute
  AdminLandIndexRoute: typeof AdminLandIndexRoute
  AdminProductIndexRoute: typeof AdminProductIndexRoute
  AdminSaleIndexRoute: typeof AdminSaleIndexRoute
  AdminStallIndexRoute: typeof AdminStallIndexRoute
  AdminLandProvinceLandLandTypeRoute: typeof AdminLandProvinceLandLandTypeRoute
  AdminCommodityProvinceCommodityIndexRoute: typeof AdminCommodityProvinceCommodityIndexRoute
  AdminCommodityRegencyCommodityIndexRoute: typeof AdminCommodityRegencyCommodityIndexRoute
  AdminLandProvinceLandIndexRoute: typeof AdminLandProvinceLandIndexRoute
  AdminLandRegencyLandIndexRoute: typeof AdminLandRegencyLandIndexRoute
  AdminProductProductBrandIndexRoute: typeof AdminProductProductBrandIndexRoute
  AdminProductProductDosageIndexRoute: typeof AdminProductProductDosageIndexRoute
  AdminRegionProvinceIndexRoute: typeof AdminRegionProvinceIndexRoute
  AdminRegionRegencyIndexRoute: typeof AdminRegionRegencyIndexRoute
  AdminSaleSaleDailyIndexRoute: typeof AdminSaleSaleDailyIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCommodityIndexRoute: AdminCommodityIndexRoute,
  AdminLandIndexRoute: AdminLandIndexRoute,
  AdminProductIndexRoute: AdminProductIndexRoute,
  AdminSaleIndexRoute: AdminSaleIndexRoute,
  AdminStallIndexRoute: AdminStallIndexRoute,
  AdminLandProvinceLandLandTypeRoute: AdminLandProvinceLandLandTypeRoute,
  AdminCommodityProvinceCommodityIndexRoute:
    AdminCommodityProvinceCommodityIndexRoute,
  AdminCommodityRegencyCommodityIndexRoute:
    AdminCommodityRegencyCommodityIndexRoute,
  AdminLandProvinceLandIndexRoute: AdminLandProvinceLandIndexRoute,
  AdminLandRegencyLandIndexRoute: AdminLandRegencyLandIndexRoute,
  AdminProductProductBrandIndexRoute: AdminProductProductBrandIndexRoute,
  AdminProductProductDosageIndexRoute: AdminProductProductDosageIndexRoute,
  AdminRegionProvinceIndexRoute: AdminRegionProvinceIndexRoute,
  AdminRegionRegencyIndexRoute: AdminRegionRegencyIndexRoute,
  AdminSaleSaleDailyIndexRoute: AdminSaleSaleDailyIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  MapIndexRoute: MapIndexRoute,
  ProductKnowledgeIndexRoute: ProductKnowledgeIndexRoute,
  ProductPotentialIndexRoute: ProductPotentialIndexRoute,
  SalesRealizationIndexRoute: SalesRealizationIndexRoute,
  StallIndexRoute: StallIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
